# Laboratory #1 algorithms

## Data types and data structures

### Basic data types

#### Strings

In [95]:
print('-----------------------------------')

string_1 = 'hello'
string_2 = "potatoes"
string_3 = '100'
string_4 = "1.234"

#string identification
'''The type of string members is str'''
print(type(string_1))
print(type(string_2))
print(type(string_3))
print(type(string_4))

print('-----------------------------------')

# string concatenation
'''Is possible to concaternate any number of strings by using
   the operator +'''
concatenated_string = string_1 + ' ' + string_2
print(concatenated_string)

print('-----------------------------------')

'''Is possible to repetively concatenate strings by using the
   operator *'''
# advance string concatenation
advance_concatenated_string = (string_1 + ' ')*2 + string_2
print(advance_concatenated_string)

print('-----------------------------------')

# string access
'''Is possible to access a specific character in a string
   by using the access operator [], the index start from 0'''
print(string_1[0])
print(string_1[1])
print(string_1[2])
print(string_1[3])
print(string_1[4])

print('-----------------------------------')

# string slicing
'''Is possible to slice a string in very different ways 
   by using the access operator [] and the operator :'''
end_sliced_string = string_2[:3]
start_sliced_string = string_2[4:]
mid_sliced_string = string_2[3:5]
step_sliced_string = string_2[::2]
other_step_sliced_string = string_2[1::2]
print(end_sliced_string)
print(start_sliced_string)
print(mid_sliced_string)
print(step_sliced_string)
print(other_step_sliced_string)

print('-----------------------------------')

# string operations

string_a = 'potatoes with salt'

# replace all 'o' with 'e'
print(string_a.replace('o', 'e'))

print('-----------------------------------')

# count the number of 't' in the string
print(string_a.count('t'))

print('-----------------------------------')

# give the index of the first intance of 't'
print(string_a.find('t'))
print(string_a[string_a.find('t')])

print('-----------------------------------')

# string formatting

#the recommended way to format strings now is

a_word = 'potatoes'
b_number = 345

# extra tip multiline strings and docstring style comments are written
# using '''

string_formatted = f'''at the end i would had wrotten {a_word}
{b_number} times'''

print(string_formatted)

-----------------------------------
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
-----------------------------------
hello potatoes
-----------------------------------
hello hello potatoes
-----------------------------------
h
e
l
l
o
-----------------------------------
pot
toes
at
ptte
oaos
-----------------------------------
petatees with salt
-----------------------------------
4
-----------------------------------
2
t
-----------------------------------
at the end i would had wrotten potatoes
345 times


#### Integers

In [96]:
print('-----------------------------------')

# integer identification
'''The type of string member is int'''
print(type(121))
print(type(2))
print(type(-3))
print(type(-2000))

print('-----------------------------------')

# integer operators
added_int = 10 + 2
subtracted_int = 10 - 2
multiplied_int = 10 * 2
'''In particular division always return a float, for integer result
   use the floor division'''
divided_int = 10 / 2
# pow operator in python
powered_int = 10 ** 2
# module operator python
moduled_int = 11 % 5
# floor division python
floor_divided_int = 11//2

print('10 + 2')
print(added_int)
print()
print('10 - 2')
print(subtracted_int)
print()
print('10 * 2')
print(multiplied_int)
print()
print('10 / 2')
print(divided_int)
print()
print('10 ** 2')
print(powered_int)
print()
print('11 % 5')
print(moduled_int)
print()
print('11 // 2')
print(floor_divided_int)

print('-----------------------------------')


-----------------------------------
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
-----------------------------------
10 + 2
12

10 - 2
8

10 * 2
20

10 / 2
5.0

10 ** 2
100

11 % 5
1

11 // 2
5
-----------------------------------


#### Floats

In [97]:
print('-----------------------------------')

# float identification
'''The type of string member is float'''
print(type(122.54))
print(type(2.34))
print(type(0.0))
print(type(-126.34))

print('-----------------------------------')

# float operators
added_float = 11 + 2.4
subtracted_float = 10.2 - 2
multiplied_float = 10.44 * 2
'''In particular division always return a float, for integer result
   use the floor division'''
divided_float = 10 / 2.6
# pow operator in python
powered_float = 10.57 ** 2
# module operator python
moduled_float = 11.45 % 5
# floor division python
floor_divided_float = 12.45//2

print('10 + 2.4')
print(added_float)
print()
print('10.2 - 2')
print(subtracted_float)
print()
print('10.44 * 2')
print(multiplied_float)
print()
print('10 / 2.6')
print(divided_float)
print()
print('10.57 ** 2')
print(powered_float)
print()
print('11.45 % 5')
print(moduled_float)
print()
print('12.45 // 2')
print(floor_divided_float)

print('-----------------------------------')


-----------------------------------
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
-----------------------------------
10 + 2.4
13.4

10.2 - 2
8.2

10.44 * 2
20.88

10 / 2.6
3.846153846153846

10.57 ** 2
111.7249

11.45 % 5
1.4499999999999993

12.45 // 2
6.0
-----------------------------------


#### Booleans

In [98]:
print('-----------------------------------')

A = True
B =  False

# boolean identification
'''The type of boolean member is bool'''
print(type(A))
print(type(B))

print('-----------------------------------')

# boolean operations
'''The basic boolean operations'''
print('and')
print('True and True')
print(True and True)
print('True and False')
print(True and False)
print('False and True')
print(False and True)
print('False and False')
print(False and False)
print('')
print('or')
print('True or True')
print(True or True)
print('True or False')
print(True or False)
print('False or True')
print(False or True)
print('False or False')
print(False or False)
print('')
print('not')
print('not True')
print(not True)
print('not False')
print(not False)


-----------------------------------
<class 'bool'>
<class 'bool'>
-----------------------------------
and
True and True
True
True and False
False
False and True
False
False and False
False

or
True or True
True
True or False
True
False or True
True
False or False
False

not
not True
False
not False
True


#### Integer, Float and String transformations

In [99]:
float_example_1 = 205.45
float_example_2 = -204.67
integer_example_1 = 20
integer_example_2 = -23
string_example_1 = '123'
string_example_2 = '254.6'

print('-----------------------------------')

print('integer transformation')
# transformations to integer
print(float_example_1, end=' -> ')
print(int(float_example_1))
print(float_example_2, end=' -> ')
print(int(float_example_2))
print(string_example_1, end=' -> ')
print(int(string_example_1))

print('-----------------------------------')

print('float transformation')
# transformation to float
print(float_example_1, end=' -> ')
print(float(integer_example_1))
print(float_example_2, end=' -> ')
print(float(integer_example_2))
print(string_example_1, end=' -> ')
print(float(string_example_1))
print(string_example_2, end=' -> ')
print(float(string_example_2))

print('-----------------------------------')

print('string transformation')
# transformation to string
print(integer_example_1, end=' -> ')
print(str(integer_example_1))
print(integer_example_2, end=' -> ')
print(str(integer_example_2))
print(float_example_1, end=' -> ')
print(str(float_example_1))
print(float_example_2, end=' -> ')
print(str(float_example_2))

print('-----------------------------------')


-----------------------------------
integer transformation
205.45 -> 205
-204.67 -> -204
123 -> 123
-----------------------------------
float transformation
205.45 -> 20.0
-204.67 -> -23.0
123 -> 123.0
254.6 -> 254.6
-----------------------------------
string transformation
20 -> 20
-23 -> -23
205.45 -> 205.45
-204.67 -> -204.67
-----------------------------------


#### Boolean evaluation

In [100]:
false_string = ''
true_string = 'anything'
false_int = 0
true_int = 23
false_float = 0.0
true_float = -122.2

print('-----------------------------------')

# bool evaluation of values
''' In python every object can have a definition for its
    boolean value'''
print("''")
print(bool(false_string))
print()
print(true_string)
print(bool(true_string))
print()
print(false_int)
print(bool(false_int))
print()
print(true_int)
print(bool(true_int))
print()
print(false_float)
print(bool(false_float))
print()
print(true_float)
print(bool(true_float))

print('-----------------------------------')


-----------------------------------
''
False

anything
True

0
False

23
True

0.0
False

-122.2
True
-----------------------------------


### Data collections

#### List

In [101]:
list_a = [1, 'a', 32.5, True]

print('-----------------------------------')

# we preferentially always create a list using []
print(list_a)

print('-----------------------------------')

''' len is a attribute tha brings the lenght of the
    list so we can use it in constant time'''

print(len(list_a))

print('-----------------------------------')

# access to the first element of a list
print(list_a[0])

print('-----------------------------------')

# access to the las element of a list, works but
print(list_a[len(list_a) - 1])

# this work better
print(list_a[-1])

print('-----------------------------------')

# we can add and remove elements

print(list_a)
list_a.append('potatoes')

print(list_a)
# remove by element
list_a.remove(32.5)
print(list_a)
# remove by index
del list_a[0]
print(list_a)

# also we can change element values

list_a[0] = 3.1416
print(list_a)


print('-----------------------------------')

-----------------------------------
[1, 'a', 32.5, True]
-----------------------------------
4
-----------------------------------
1
-----------------------------------
True
True
-----------------------------------
[1, 'a', 32.5, True]
[1, 'a', 32.5, True, 'potatoes']
[1, 'a', True, 'potatoes']
['a', True, 'potatoes']
[3.1416, True, 'potatoes']
-----------------------------------


In [102]:
print('-----------------------------------')

list_b = [10, 20, 30, 40, 50, 60,
          70, 80, 90, 100]

# list support slicing as string does

print(list_b[::2])
print(list_b[1::2])
print(list_b[3:])
print(list_b[:5])

# extra trick reverse for strings and for list

print(list_b[::-1])

print('-----------------------------------')

-----------------------------------
[10, 30, 50, 70, 90]
[20, 40, 60, 80, 100]
[40, 50, 60, 70, 80, 90, 100]
[10, 20, 30, 40, 50]
[100, 90, 80, 70, 60, 50, 40, 30, 20, 10]
-----------------------------------


#### Tuple

In [103]:
'''A tuple is a static connection so at difference of
   list you can't change values of the elements and 
   can't add or remove elements'''

print('-----------------------------------')

tuple_a = (23, 45, 234.56, True, 'hello')
print(tuple_a)

print('-----------------------------------')

#it still support slicing
print(tuple_a[::2])
print(tuple_a[1::2])
print(tuple_a[3:])
print(tuple_a[:3])
print(tuple_a[::-1])

# extra for create a single element tuple in case of need

x = (123)
y = (123, )

# only y will be a tuple

print('-----------------------------------')

print(type(x))
print(type(y))

print('-----------------------------------')

-----------------------------------
(23, 45, 234.56, True, 'hello')
-----------------------------------
(23, 234.56, 'hello')
(45, True)
(True, 'hello')
(23, 45, 234.56)
('hello', True, 234.56, 45, 23)
-----------------------------------
<class 'int'>
<class 'tuple'>
-----------------------------------


In [104]:
# for demostration

y = (123, )

y[0] = 'potato'

TypeError: 'tuple' object does not support item assignment

In [ ]:
# for demostration

y = (123, )

del y[0]

TypeError: 'tuple' object doesn't support item deletion

#### Set

In [ ]:
'''A set is a unordered collection that dont allow for duplicates
   and support set operations'''

# for create a set

print('-----------------------------------')

list_a = [10, 20, 30, 40, 50]
tuple_a = (40, 50, 60, 70, 80)

set_a = set(list_a)
set_b = set(tuple_a)
set_c = {70, 80, 90, 100, 120}

print(set_a)
print(type(set_a))
print(set_b)
print(type(set_b))
print(set_c)
print(type(set_c))

# set operations

print('-----------------------------------')

print(set_a, ' union ', set_b)
print(set_a.union(set_b))

print('-----------------------------------')

print(set_a, ' intersection ', set_b)
print(set_a.intersection(set_b))

print('-----------------------------------')

print(set_a, ' difference ', set_b)
print(set_a.difference(set_b))

print('-----------------------------------')

print(set_a, ' symmettic difference ', set_b)
print(set_a.symmetric_difference(set_b))

print('-----------------------------------')

-----------------------------------
{40, 10, 50, 20, 30}
<class 'set'>
{70, 40, 80, 50, 60}
<class 'set'>
{80, 100, 70, 120, 90}
<class 'set'>
-----------------------------------
{40, 10, 50, 20, 30}  union  {70, 40, 80, 50, 60}
{70, 40, 10, 80, 50, 20, 60, 30}
-----------------------------------
{40, 10, 50, 20, 30}  intersection  {70, 40, 80, 50, 60}
{40, 50}
-----------------------------------
{40, 10, 50, 20, 30}  difference  {70, 40, 80, 50, 60}
{10, 20, 30}
-----------------------------------
{40, 10, 50, 20, 30}  symmettic difference  {70, 40, 80, 50, 60}
{80, 20, 70, 10, 60, 30}
-----------------------------------


#### Dict

In [ ]:
# Dict are the hash implementation of python
# it maps a value to a given unique key

# create a dict

dict_a = {1: 'potatoes', 'strawberry': 345, 120: True}

print('-----------------------------------')

print(dict_a)
print(type(dict_a))

print('-----------------------------------')

# access to a object in a dict

print(dict_a['strawberry'])
print(dict_a[120])

print('-----------------------------------')

# add a value to a dict

print(dict_a)
dict_a['berry'] = False
print(dict_a)

print('-----------------------------------')

# modify a value in a dict

print(dict_a)
dict_a['berry'] = True
print(dict_a)

print('-----------------------------------')

-----------------------------------
{1: 'potatoes', 'strawberry': 345, 120: True}
<class 'dict'>
-----------------------------------
345
True
-----------------------------------
{1: 'potatoes', 'strawberry': 345, 120: True}
{1: 'potatoes', 'strawberry': 345, 120: True, 'berry': False}
-----------------------------------
{1: 'potatoes', 'strawberry': 345, 120: True, 'berry': False}
{1: 'potatoes', 'strawberry': 345, 120: True, 'berry': True}
-----------------------------------


## Logical operations and loops

### Logical operations

#### Basic logical operations

In [ ]:
'''in python we can make logical operations with booleans, with
   any element that have a boolean value and with any function
   that returns a element with boolean value or a boolean'''

# basic boolean functions

print('-----------------------------------')

print('equality')
print('a == b')
print('2 == 2')
print(2 == 2)
print('2 == 3')
print(2 == 3)
print('-----------------------------------')
print('inequality')
print('a != b')
print('2 != 2')
print(2 != 2)
print('2 != 3')
print(2 != 3)
print('-----------------------------------')
print('greater')
print('a > b')
print('3 > 2')
print(3 > 2)
print('1 > 2')
print(1 > 2)
print('-----------------------------------')
print('lesser')
print('a < b')
print('3 < 2')
print(3 < 2)
print('1 < 2')
print(1 < 2)
print('-----------------------------------')
print('greater or equal')
print('a >= b')
print('3 >= 2')
print(3 >= 2)
print('1 >= 2')
print(1 >= 2)
print('-----------------------------------')
print('lesser or equal')
print('a <= b')
print('3 <= 2')
print(2 <= 2)
print('3 <= 2')
print(3 <= 2)
print('-----------------------------------')


-----------------------------------
equality
a == b
2 == 2
True
2 == 3
False
-----------------------------------
inequality
a != b
2 != 2
False
2 != 3
True
-----------------------------------
greater
a > b
3 > 2
True
1 > 2
False
-----------------------------------
lesser
a < b
3 < 2
False
1 < 2
True
-----------------------------------
greater or equal
a >= b
3 >= 2
True
1 >= 2
False
-----------------------------------
lesser or equal
a <= b
3 <= 2
True
3 <= 2
False
-----------------------------------


In [ ]:
# also python can proccess pertenency operations

print('-----------------------------------')
print('pertenency')
print('a in collection')
print('2 in [2, 3, 4]')
print(2 in [2, 3, 4])
print('5 in (2, 3, 4)')
print(5 in (2, 3, 4))
print('-----------------------------------')


-----------------------------------
pertenency
a in collection
2 in [2, 3, 4]
True
5 in (2, 3, 4)
False
-----------------------------------


In [ ]:
# also can process a strict identity

print('-----------------------------------')
print('strict identity')
a = c = [2, 3, 4]
b = (2, 3, 4)
b = list(b)
print('a -> ',a)
print('b -> ',b)
print('c -> ',c)
print('a is c')
print(a is c)
print('a is b')
print(a is b)
print('-----------------------------------')


-----------------------------------
strict identity
a ->  [2, 3, 4]
b ->  [2, 3, 4]
c ->  [2, 3, 4]
a is c
True
a is b
False
-----------------------------------


#### Logical connectors and Not

In [ ]:
'''We can complement all the functions we had seen before 
   with the use of logical connectors and the not statement'''

'''As we saw in boolean operations in the booleans section the 
   connectors can be use with booleans
   and also with the functions before and not'''

print('-----------------------------------')

print('not')
print('not 2 == 2')
print(not 2==2)
print('not False')
print(not False)

print('-----------------------------------')

-----------------------------------
not
not 2 == 2
False
not False
True
-----------------------------------


#### Advance logical statements

In [ ]:
# as example we can replicate a xor door using previous statements

print('-----------------------------------')

print('(a and not b) or (not a and b)')

print('-----------------------------------')

a = b = True
print((a and not b) or (not a and b))

print('-----------------------------------')

a = True
b = False
print((a and not b) or (not a and b))

print('-----------------------------------')

a = False
b = True
print((a and not b) or (not a and b))

print('-----------------------------------')

a = b = False
print((a and not b) or (not a and b))

print('-----------------------------------')

-----------------------------------
(a and not b) or (not a and b)
-----------------------------------
False
-----------------------------------
True
-----------------------------------
True
-----------------------------------
False
-----------------------------------


### Loops

#### If loop

In [ ]:
'''The objective of the if loop is to let us execute different code
   in dependance of a given condition'''

age = 20

if age < 10:
    print('you are a child')
elif 10 < age < 18:
    print('you are a teenager')
else: 
    print('you are a adult')

you are a adult


#### While loop

In [ ]:
'''The objective of the while loop is to execute a operation while
   a condition is meet'''

a = 1
b = 1

print(a)

while b < 500:
    print(b)
    new_b = a + b
    a = b
    b = new_b

# this code print the fibbonacci serie while b is less than 500

1
1
2
3
5
8
13
21
34
55
89
144
233
377


#### For loop

In [ ]:
'''The objective of the for loop is to iterate through a value collection
   for make a operation with his values or for repeat a process given 
   a specific quantity of times'''

print('-----------------------------------')

# this code exten the word potato and print it 10 times

word = 'potato'

for _ in range(10):
    print(word)
    word += 'tato'

print('-----------------------------------')

# this code announce that the walls in the list was destroyed

for wall in ['Maria', 'Rose', 'Sina']:
    print(f'They destroy the wall {wall}')

print('-----------------------------------')

-----------------------------------
potato
potatotato
potatotatotato
potatotatotatotato
potatotatotatotatotato
potatotatotatotatotatotato
potatotatotatotatotatotatotato
potatotatotatotatotatotatotatotato
potatotatotatotatotatotatotatotatotato
potatotatotatotatotatotatotatotatotatotato
-----------------------------------
They destroy the wall Maria
They destroy the wall Rose
They destroy the wall Sina
-----------------------------------


#### Break and continue

In [ ]:
'''Break and continue are commands that are used respectively for exit a loop
   or for step over this part of the loop execution'''

''' in this particular case we are going to use for else a for loop that
    after end without use a break execute the code inside else'''

print('-----------------------------------')

received = []

for person in ['juan', 'luna', 'maria']:
    if person == 'pepe':
        print('in this restaurant we do not receive pepe or his friends')
        break
    if person == 'luna':
        print('in this restauran we do not receive luna')
        continue
    received.append(person)
else:
    print(received, 'please enter')

print('-----------------------------------')

received = []

for person in ['juan', 'maria', 'pepe']:
    if person == 'pepe':
        print('in this restaurant we do not receive pepe or his friends')
        break
    if person == 'luna':
        print('in this restauran we do not receive luna')
        continue
    received.append(person)
else:
    print(received, 'please enter')

print('-----------------------------------')

-----------------------------------
in this restauran we do not receive luna
['juan', 'maria'] please enter
-----------------------------------
in this restaurant we do not receive pepe or his friends
-----------------------------------


#### Extra: Exceptions

In [ ]:
'''Commonly when defending our code of bad data we
   can use exceptions in python over if, that is because
   python philosopy benefit the use of exceptions giving it faster
   times'''

'''There is exception for practically all functions in
   python and write quality code, specially in advance
   code means to keep them in mind'''


# for example a division

a = 10
b = 0

print('-----------------------------------')
# we can do this

if not b == 0:
    print(a / b)
else:
    print('You cant divide by 0')

print('-----------------------------------')
# but is better to do

try:
    print(a / b)
except ZeroDivisionError:
    print('You cant divide by 0')

print('-----------------------------------')

-----------------------------------
You cant divide by 0
-----------------------------------
You cant divide by 0
-----------------------------------


### Collection comprehension

In [ ]:
'''in python some of the basic collections can be written using comprehension
   as shown next'''

list_odd_until_one_hundred = [x for x in range(101) if x % 2 == 1]
print(list_odd_until_one_hundred)

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99]


In [ ]:
list_congruence_7_mod_11 = [x for x in range(1001) if x % 11 == 7]
# enumerate simply generate tuples enumerated by order
# for can be used for unpack some collections
dict_congruence_7_mod_11 = {(x + 1):y for x, y in 
                            enumerate(list_congruence_7_mod_11)}

print(dict_congruence_7_mod_11)

{1: 7, 2: 18, 3: 29, 4: 40, 5: 51, 6: 62, 7: 73, 8: 84, 9: 95, 10: 106, 11: 117, 12: 128, 13: 139, 14: 150, 15: 161, 16: 172, 17: 183, 18: 194, 19: 205, 20: 216, 21: 227, 22: 238, 23: 249, 24: 260, 25: 271, 26: 282, 27: 293, 28: 304, 29: 315, 30: 326, 31: 337, 32: 348, 33: 359, 34: 370, 35: 381, 36: 392, 37: 403, 38: 414, 39: 425, 40: 436, 41: 447, 42: 458, 43: 469, 44: 480, 45: 491, 46: 502, 47: 513, 48: 524, 49: 535, 50: 546, 51: 557, 52: 568, 53: 579, 54: 590, 55: 601, 56: 612, 57: 623, 58: 634, 59: 645, 60: 656, 61: 667, 62: 678, 63: 689, 64: 700, 65: 711, 66: 722, 67: 733, 68: 744, 69: 755, 70: 766, 71: 777, 72: 788, 73: 799, 74: 810, 75: 821, 76: 832, 77: 843, 78: 854, 79: 865, 80: 876, 81: 887, 82: 898, 83: 909, 84: 920, 85: 931, 86: 942, 87: 953, 88: 964, 89: 975, 90: 986, 91: 997}


## Functions and OOP

### Functions

#### User defined functions

In [ ]:
'''For define a function we only need to use de word def and describe
   the inputs of our function, at the end we use return for our output'''

print('-----------------------------------')

def sum_elements(a, b):
   return(a + b)

print(sum_elements(2, 3))

print('-----------------------------------')

# we can use a n number of entries using *args

def sum_a_lot_of_elements(*args):
   r = 0
   for x in args:
      r += x
   return r

print(sum_a_lot_of_elements(1, 2, 3, 4, 5))

print('-----------------------------------')

# we can use name argument using **kwargs

def travel_plan(**kwargs):
   value = f'we are going to {kwargs["ciudad"]} the day {kwargs["fecha"]}'
   return value

print(travel_plan(ciudad='bogota', fecha=10))

print('-----------------------------------')

-----------------------------------
5
-----------------------------------
15
-----------------------------------
we are going to bogota the day 10
-----------------------------------


#### Lambda functions

In [ ]:
'''lambda functions are a way to make reduced functions declarations 
   in case of need'''

print('-----------------------------------')

a = lambda x : x[-1]

print(a([1,2,3,4,5]))

print('-----------------------------------')

b = lambda x, y: (x ** y) - 2

print(b(11, 2))

print('-----------------------------------')

-----------------------------------
5
-----------------------------------
119
-----------------------------------


#### Built-in functions

In [ ]:
'''range is a generator function that generates number given
   a start(inclusive), end(exclusive), step'''

# * is the unpack operator and let us see the range results

print('-----------------------------------')

print([*range(4,11,2)])

print('-----------------------------------')

print([*range(10,0,-1)])

print('-----------------------------------')

-----------------------------------
[4, 6, 8, 10]
-----------------------------------
[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]
-----------------------------------


In [ ]:
'''map function is a function that given a list apply a function 
   to every element of the list, is a generator so again msut use *'''

not_squared_numbers = [32, 11, 24, 2, 3, 4, 8, 9]
squared_numbers = [*map(lambda x : x ** 2, not_squared_numbers)]
print(squared_numbers)

[1024, 121, 576, 4, 9, 16, 64, 81]


In [ ]:
'''sorted in a function that can sort a list given certain parameters'''

print('-----------------------------------')

A = [10, 2, 3, 65, 1, 75, 82, 10]

# sort normally
print(sorted(A))

print('-----------------------------------')

# sort inverse
print(sorted(A, reverse=True))

print('-----------------------------------')

# sort by function
print(sorted(A, key=lambda x:x%10))

print('-----------------------------------')

-----------------------------------
[1, 2, 3, 10, 10, 65, 75, 82]
-----------------------------------
[82, 75, 65, 10, 10, 3, 2, 1]
-----------------------------------
[10, 10, 1, 2, 82, 3, 65, 75]
-----------------------------------


### Object Oriented Programming

In [ ]:
'''a class is no more no less than a data type that acts as container for data
   and for methods that will ve applied for manipulate the data in it'''

#remember __methods__ are special methods called for specific situations

print('-----------------------------------')

class car:
    def __init__(self, model, color):
        self.model = model
        self.color = color
    def describe(self):
        return f'car of color {self.color} and model {self.model}'

A = car('ferrari', 'red')
print(A.describe())

print('-----------------------------------')

# we can change the values on fly
A.color = 'blue'
print(A.describe())

# we can use inheritance also for extend functionalities of classes

print('-----------------------------------')

class readable_list(list):
    def __repr__(self):
        r = ''
        for x in self[:-1]:
            r += str(x) + ', '
        return r + str(self[-1])

B = readable_list(('potatoes', 21 ,32.4))
print(B)

print('-----------------------------------')


-----------------------------------
car of color red and model ferrari
-----------------------------------
car of color blue and model ferrari
-----------------------------------
potatoes, 21, 32.4
-----------------------------------


## NumPy and pandas

### NumPy

In [ ]:
'''NumPy is a library that provides numerical methods,
   structures and functions for scientific, statisticals and general
   scientific applications'''

import numpy as np

#### NumPy arrays

In [ ]:
'''a array is a numpy multidimensional data structure that support
   a variety of special numpy operations and manipulations'''

# in this case a 3 dimesional array
array = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
                  [[10, 11, 12], [13, 14, 15],[16, 17, 18]],
                  [[19, 20, 21], [22, 23, 24], [25, 26, 27]]])
print(array)
print()
print(type(array))
print()
# the shape of the array through is 3 dimensions
print(array.shape)
print()
# access to every dimesion by position
print(array[1])
print()
print(array[:,1])
print()
print(array[:,:,1])
print()

# for example for access to the number 15
print(array[1,1,2])
print()

#for access to the numbers 6, 15, 24
print(array[:,1,2])


[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]

<class 'numpy.ndarray'>

(3, 3, 3)

[[10 11 12]
 [13 14 15]
 [16 17 18]]

[[ 4  5  6]
 [13 14 15]
 [22 23 24]]

[[ 2  5  8]
 [11 14 17]
 [20 23 26]]

15

[ 6 15 24]


#### Array functions

In [ ]:
array = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
                  [[10, 11, 12], [13, 14, 15],[16, 17, 18]],
                  [[19, 20, 21], [22, 23, 24], [25, 26, 27]]])

# the mean of array values
print(np.mean(array))
# the sum of array values
print(np.sum(array))
# the max of array values
print(np.max(array))
# the standard deviation of array values
print(np.std(array))


14.0
378
27
7.788880963698615


### Pandas

In [ ]:
'''Pandas is a data manipulation library that is thought for let us
   refine, analyze and use data in a easy way'''

import pandas as pd

#### Series

In [ ]:
'''series are pandas labeled one dimensional collections'''

# we can define the index that in default start from 0 and also give a name
serie = pd.Series([6, 7, 8, 9, 10], index=['a', 'b', 'c', 'd', 'e'],
                  name='random_serie')
print(serie)
print()

# we can change index and name manually
serie.index = pd.Series(['z', 'y', 'x', 'w', 'v']) # type: ignore
serie.name = 'random'
print(serie)
print()

# it supports indexing
print(serie[::-1])
print()
print(serie[::2])
print()
print(serie[0:3])
print()

# also can be accesed by index
print(serie['w'])
print()

# and even have a statistic description
print(serie.describe())

a     6
b     7
c     8
d     9
e    10
Name: random_serie, dtype: int64

z     6
y     7
x     8
w     9
v    10
Name: random, dtype: int64

v    10
w     9
x     8
y     7
z     6
Name: random, dtype: int64

z     6
x     8
v    10
Name: random, dtype: int64

z    6
y    7
x    8
Name: random, dtype: int64

9

count     5.000000
mean      8.000000
std       1.581139
min       6.000000
25%       7.000000
50%       8.000000
75%       9.000000
max      10.000000
Name: random, dtype: float64


#### Time index

In [ ]:
'''date_range function is a function that let us generate a range of dates
   that give us access to very powerful data modification in pandas'''

# head let us see only a little number of data
# tail is equivalent for last data
# create a time indexed series
time_index = pd.date_range('2022-01-01',periods = 365, freq = 'D')
data = pd.Series([x ** 2 for x in range(365)], index=time_index)
print(data.head())
print()
# we can access elements like this
print(data['2022-2-5'])
print()
# we can accces a range like this
print(data['2022-2-5':'2022-7-7'].head())
print()
# we can access data given conditions
print(data[data % 2 == 1].tail())
print()

2022-01-01     0
2022-01-02     1
2022-01-03     4
2022-01-04     9
2022-01-05    16
Freq: D, dtype: int64

1225

2022-02-05    1225
2022-02-06    1296
2022-02-07    1369
2022-02-08    1444
2022-02-09    1521
Freq: D, dtype: int64

2022-12-22    126025
2022-12-24    127449
2022-12-26    128881
2022-12-28    130321
2022-12-30    131769
dtype: int64



## Pandas-Resampling and DataFrame

### Fetching data

In [ ]:
import yfinance as yf

# we are fetching the data of amd company from yahoo finance services

amd = yf.Ticker('AMD')

amd = amd.history(start='2020-01-01', end='2022-01-01')

#it generate a pandas Dataframe

In [ ]:
amd

Open        High         Low       Close    Volume  \
Date                                                                   
2020-01-02   46.860001   49.250000   46.630001   49.099998  80331100   
2020-01-03   48.029999   49.389999   47.540001   48.599998  73127400   
2020-01-06   48.020000   48.860001   47.860001   48.389999  47934900   
2020-01-07   49.349998   49.389999   48.040001   48.250000  58061400   
2020-01-08   47.849998   48.299999   47.139999   47.830002  53767000   
...                ...         ...         ...         ...       ...   
2021-12-27  147.509995  154.889999  147.250000  154.360001  53296400   
2021-12-28  155.880005  156.729996  151.380005  153.149994  58699100   
2021-12-29  152.820007  154.339996  147.289993  148.259995  51300200   
2021-12-30  147.440002  148.850006  144.850006  145.149994  44358000   
2021-12-31  146.160004  148.610001  143.550003  143.899994  49448100   

            Dividends  Stock Splits  
Date                                 
2020-01-02          0             0  
2020-01-03          0             0  
2020-01-06          0             0  
2020-01-07          0             0  
2020-01-08          0             0  
...               ...           ...  
2021-12-27          0             0  
2021-12-28          0             0  
2021-12-29          0             0  
2021-12-30          0             0  
2021-12-31          0             0  

[505 rows x 7 columns]

In [ ]:
# we can get only one of the dataframe colums in this case 
# the market value at stocks close in the 2021
amd_close = amd['Close']['2021']
amd_close

Date
2021-01-04     92.300003
2021-01-05     92.769997
2021-01-06     90.330002
2021-01-07     95.160004
2021-01-08     94.580002
                 ...    
2021-12-27    154.360001
2021-12-28    153.149994
2021-12-29    148.259995
2021-12-30    145.149994
2021-12-31    143.899994
Name: Close, Length: 252, dtype: float64

In [ ]:
#we are getting the close data from december of 2021

print(amd_close['2021-12'])

Date
2021-12-01    149.110001
2021-12-02    150.679993
2021-12-03    144.009995
2021-12-06    139.059998
2021-12-07    144.850006
2021-12-08    145.240005
2021-12-09    138.100006
2021-12-10    138.550003
2021-12-13    133.800003
2021-12-14    135.600006
2021-12-15    146.500000
2021-12-16    138.639999
2021-12-17    137.750000
2021-12-20    135.800003
2021-12-21    144.250000
2021-12-22    143.880005
2021-12-23    146.139999
2021-12-27    154.360001
2021-12-28    153.149994
2021-12-29    148.259995
2021-12-30    145.149994
2021-12-31    143.899994
Name: Close, dtype: float64


In [ ]:
# Getting data from september to december
print(amd_close['2021-09':'2021-12'])

Date
2021-09-01    109.989998
2021-09-02    109.199997
2021-09-03    109.919998
2021-09-07    109.150002
2021-09-08    106.169998
                 ...    
2021-12-27    154.360001
2021-12-28    153.149994
2021-12-29    148.259995
2021-12-30    145.149994
2021-12-31    143.899994
Name: Close, Length: 85, dtype: float64


### Resampling

In [ ]:
# we can resample hour data in different periods of time
# and using different statistical description
amd_by_month = amd.resample('M').mean()
amd_by_year = amd.resample('Y').mean()
amd_by_week = amd.resample('W').mean()

In [ ]:
amd_by_year.head()

Open        High        Low       Close        Volume  \
Date                                                                      
2020-12-31   65.599091   66.924032  64.169328   65.619723  6.157304e+07   
2021-12-31  101.113770  102.968730  99.248413  101.145873  5.124813e+07   

            Dividends  Stock Splits  
Date                                 
2020-12-31        0.0           0.0  
2021-12-31        0.0           0.0

In [ ]:
amd_by_month.head()

Open       High        Low      Close        Volume  \
Date                                                                   
2020-01-31  49.077619  49.863334  48.346191  49.197142  5.847057e+07   
2020-02-29  51.120526  52.463684  50.022632  51.376842  6.753405e+07   
2020-03-31  44.465909  46.059091  42.778182  44.424091  9.526760e+07   
2020-04-30  52.033809  53.435714  50.806667  52.063810  8.164837e+07   
2020-05-31  53.568000  54.602000  52.276000  53.503000  5.963490e+07   

            Dividends  Stock Splits  
Date                                 
2020-01-31        0.0           0.0  
2020-02-29        0.0           0.0  
2020-03-31        0.0           0.0  
2020-04-30        0.0           0.0  
2020-05-31        0.0           0.0

In [ ]:
amd_by_week.head()

Open       High        Low      Close      Volume  Dividends  \
Date                                                                            
2020-01-05  47.445000  49.320000  47.085001  48.849998  76729250.0        0.0   
2020-01-12  48.683999  49.160000  47.886000  48.322000  56081960.0        0.0   
2020-01-19  48.980000  49.668001  48.632001  49.242000  45930260.0        0.0   
2020-01-26  51.552500  52.062501  50.527501  51.134999  52501875.0        0.0   
2020-02-02  48.242001  49.220000  47.280000  48.615999  70870980.0        0.0   

            Stock Splits  
Date                      
2020-01-05           0.0  
2020-01-12           0.0  
2020-01-19           0.0  
2020-01-26           0.0  
2020-02-02           0.0

In [ ]:
amd_by_week_max = amd.resample('W').max()

In [ ]:
amd_by_week_max

Open        High         Low       Close     Volume  \
Date                                                                    
2020-01-05   48.029999   49.389999   47.540001   49.099998   80331100   
2020-01-12   49.349998   49.959999   48.389999   48.970001   76512800   
2020-01-19   50.200001   51.049999   49.900002   50.930000   58898900   
2020-01-26   52.279999   52.810001   51.200001   51.709999   80004900   
2020-02-02   50.029999   50.849998   49.480000   50.529999  112349900   
...                ...         ...         ...         ...        ...   
2021-12-05  163.279999  164.460007  156.100006  161.910004   75182500   
2021-12-12  145.160004  147.039993  142.699997  145.240005   66776500   
2021-12-19  147.000000  147.929993  137.020004  146.500000   72425800   
2021-12-26  143.889999  149.020004  143.850006  146.139999   57785200   
2022-01-02  155.880005  156.729996  151.380005  154.360001   58699100   

            Dividends  Stock Splits  
Date                                 
2020-01-05          0             0  
2020-01-12          0             0  
2020-01-19          0             0  
2020-01-26          0             0  
2020-02-02          0             0  
...               ...           ...  
2021-12-05          0             0  
2021-12-12          0             0  
2021-12-19          0             0  
2021-12-26          0             0  
2022-01-02          0             0  

[105 rows x 7 columns]

In [ ]:
amd_by_week_std = amd.resample('W').std()

In [ ]:
amd_by_week_std

Open      High       Low     Close        Volume  Dividends  \
Date                                                                          
2020-01-05  0.827314  0.098995  0.643467  0.353553  5.093785e+06        0.0   
2020-01-12  0.703086  0.620363  0.460413  0.416797  1.260785e+07        0.0   
2020-01-19  0.759112  0.963727  0.817479  1.108387  1.151509e+07        0.0   
2020-01-26  0.557218  0.501157  0.740602  0.589096  1.878420e+07        0.0   
2020-02-02  1.274389  1.104762  1.429983  1.408875  2.443522e+07        0.0   
...              ...       ...       ...       ...           ...        ...   
2021-12-05  6.372681  5.708500  6.487057  7.235165  7.626321e+06        0.0   
2021-12-12  1.954511  2.862976  3.530591  3.565398  1.044389e+07        0.0   
2021-12-19  5.740552  4.593532  2.515982  4.875275  1.160933e+07        0.0   
2021-12-26  3.721516  4.420728  4.740336  4.586402  8.029474e+06        0.0   
2022-01-02  4.183867  3.717385  2.990130  4.672413  5.250732e+06        0.0   

            Stock Splits  
Date                      
2020-01-05           0.0  
2020-01-12           0.0  
2020-01-19           0.0  
2020-01-26           0.0  
2020-02-02           0.0  
...                  ...  
2021-12-05           0.0  
2021-12-12           0.0  
2021-12-19           0.0  
2021-12-26           0.0  
2022-01-02           0.0  

[105 rows x 7 columns]

In [ ]:
# we can even do it my multiplication of the time ranges
amd_by_semester = amd.resample("6M").mean()

In [ ]:
amd_by_semester

Open        High         Low       Close        Volume  \
Date                                                                       
2020-01-31   49.077619   49.863334   48.346191   49.197142  5.847057e+07   
2020-07-31   52.453413   53.758254   51.161032   52.528730  7.162412e+07   
2021-01-31   85.670240   87.124320   83.889920   85.535360  5.058646e+07   
2021-07-31   83.584206   84.874365   82.178492   83.610000  4.422665e+07   
2022-01-31  123.337289  125.930093  120.964019  123.476729  5.929086e+07   

            Dividends  Stock Splits  
Date                                 
2020-01-31        0.0           0.0  
2020-07-31        0.0           0.0  
2021-01-31        0.0           0.0  
2021-07-31        0.0           0.0  
2022-01-31        0.0           0.0

In [ ]:
# for example for calculation of monthly returns
amd_by_month_agg = amd.resample('M').agg(lambda x: x[-1])

In [ ]:
amd_by_month_agg

Open        High         Low       Close     Volume  \
Date                                                                    
2020-01-31   48.400002   48.580002   46.790001   47.000000   60322400   
2020-02-29   41.360001   46.150002   41.040001   45.480000  100331800   
2020-03-31   47.930000   48.529999   45.160000   45.480000   83483700   
2020-04-30   53.430000   54.290001   52.029999   52.389999   65543900   
2020-05-31   52.070000   53.799999   51.849998   53.799999   64666700   
2020-06-30   51.160000   52.770000   50.820000   52.610001   42275700   
2020-07-31   78.669998   78.959999   75.360001   77.430000   71621600   
2020-08-31   85.050003   92.639999   85.050003   90.820000   90655900   
2020-09-30   81.750000   82.940002   80.660004   81.989998   51533700   
2020-10-31   77.089996   77.699997   74.230003   75.290001   51349000   
2020-11-30   87.330002   92.739998   86.529999   92.660004   84483000   
2020-12-31   92.099998   92.300003   90.870003   91.709999   24930700   
2021-01-31   87.559998   88.330002   85.019997   85.639999   56735800   
2021-02-28   83.570000   85.589996   82.910004   84.510002   48962900   
2021-03-31   76.570000   79.129997   76.519997   78.500000   43659500   
2021-04-30   82.970001   84.099998   81.419998   81.620003   46601900   
2021-05-31   78.660004   81.089996   78.660004   80.080002   40952700   
2021-06-30   90.820000   94.339996   90.599998   93.930000   70721500   
2021-07-31  101.599998  106.970001  101.379997  106.190002  125567000   
2021-08-31  111.260002  111.260002  109.029999  110.720001   49339000   
2021-09-30  102.080002  104.440002  101.989998  102.900002   57588500   
2021-10-31  120.949997  122.570000  119.879997  120.230003   43289800   
2021-11-30  163.279999  164.460007  155.679993  158.369995   75182500   
2021-12-31  146.160004  148.610001  143.550003  143.899994   49448100   

            Dividends  Stock Splits  
Date                                 
2020-01-31          0             0  
2020-02-29          0             0  
2020-03-31          0             0  
2020-04-30          0             0  
2020-05-31          0             0  
2020-06-30          0             0  
2020-07-31          0             0  
2020-08-31          0             0  
2020-09-30          0             0  
2020-10-31          0             0  
2020-11-30          0             0  
2020-12-31          0             0  
2021-01-31          0             0  
2021-02-28          0             0  
2021-03-31          0             0  
2021-04-30          0             0  
2021-05-31          0             0  
2021-06-30          0             0  
2021-07-31          0             0  
2021-08-31          0             0  
2021-09-30          0             0  
2021-10-31          0             0  
2021-11-30          0             0  
2021-12-31          0             0

In [ ]:
# also we can get fast statistical description

amd_by_month_agg.describe()

Open        High         Low       Close        Volume  \
count   24.000000   24.000000   24.000000   24.000000  2.400000e+01   
mean    85.075833   87.178750   83.626250   85.552083  6.246864e+07   
std     29.919258   30.031731   29.108961   29.212319  2.240498e+07   
min     41.360001   46.150002   41.040001   45.480000  2.493070e+07   
25%     70.785000   71.847498   68.680002   69.917500  4.837265e+07   
50%     83.270000   84.844997   82.165001   83.250000  5.716215e+07   
75%     94.474998   96.864998   93.497501   96.172501  7.251182e+07   
max    163.279999  164.460007  155.679993  158.369995  1.255670e+08   

       Dividends  Stock Splits  
count       24.0          24.0  
mean         0.0           0.0  
std          0.0           0.0  
min          0.0           0.0  
25%          0.0           0.0  
50%          0.0           0.0  
75%          0.0           0.0  
max          0.0           0.0

In [ ]:
# we can use diff for get the differenc from consecutive months

amd_by_month_agg.diff()

Open       High        Low      Close      Volume  Dividends  \
Date                                                                            
2020-01-31        NaN        NaN        NaN        NaN         NaN        NaN   
2020-02-29  -7.040001  -2.430000  -5.750000  -1.520000  40009400.0        0.0   
2020-03-31   6.570000   2.379997   4.119999   0.000000 -16848100.0        0.0   
2020-04-30   5.500000   5.760002   6.869999   6.910000 -17939800.0        0.0   
2020-05-31  -1.360001  -0.490002  -0.180000   1.410000   -877200.0        0.0   
2020-06-30  -0.910000  -1.029999  -1.029999  -1.189999 -22391000.0        0.0   
2020-07-31  27.509998  26.189999  24.540001  24.820000  29345900.0        0.0   
2020-08-31   6.380005  13.680000   9.690002  13.389999  19034300.0        0.0   
2020-09-30  -3.300003  -9.699997  -4.389999  -8.830002 -39122200.0        0.0   
2020-10-31  -4.660004  -5.240005  -6.430000  -6.699997   -184700.0        0.0   
2020-11-30  10.240005  15.040001  12.299995  17.370003  33134000.0        0.0   
2020-12-31   4.769997  -0.439995   4.340004  -0.950005 -59552300.0        0.0   
2021-01-31  -4.540001  -3.970001  -5.850006  -6.070000  31805100.0        0.0   
2021-02-28  -3.989998  -2.740005  -2.109993  -1.129997  -7772900.0        0.0   
2021-03-31  -7.000000  -6.459999  -6.390007  -6.010002  -5303400.0        0.0   
2021-04-30   6.400002   4.970001   4.900002   3.120003   2942400.0        0.0   
2021-05-31  -4.309998  -3.010002  -2.759995  -1.540001  -5649200.0        0.0   
2021-06-30  12.159996  13.250000  11.939995  13.849998  29768800.0        0.0   
2021-07-31  10.779999  12.630005  10.779999  12.260002  54845500.0        0.0   
2021-08-31   9.660004   4.290001   7.650002   4.529999 -76228000.0        0.0   
2021-09-30  -9.180000  -6.820000  -7.040001  -7.820000   8249500.0        0.0   
2021-10-31  18.869995  18.129997  17.889999  17.330002 -14298700.0        0.0   
2021-11-30  42.330002  41.890007  35.799995  38.139992  31892700.0        0.0   
2021-12-31 -17.119995 -15.850006 -12.129990 -14.470001 -25734400.0        0.0   

            Stock Splits  
Date                      
2020-01-31           NaN  
2020-02-29           0.0  
2020-03-31           0.0  
2020-04-30           0.0  
2020-05-31           0.0  
2020-06-30           0.0  
2020-07-31           0.0  
2020-08-31           0.0  
2020-09-30           0.0  
2020-10-31           0.0  
2020-11-30           0.0  
2020-12-31           0.0  
2021-01-31           0.0  
2021-02-28           0.0  
2021-03-31           0.0  
2021-04-30           0.0  
2021-05-31           0.0  
2021-06-30           0.0  
2021-07-31           0.0  
2021-08-31           0.0  
2021-09-30           0.0  
2021-10-31           0.0  
2021-11-30           0.0  
2021-12-31           0.0

In [ ]:
# also we can get a change in percentage

daily_return = amd_by_month_agg.pct_change()
daily_return

Open      High       Low     Close    Volume  Dividends  \
Date                                                                      
2020-01-31       NaN       NaN       NaN       NaN       NaN        NaN   
2020-02-29 -0.145455 -0.050021 -0.122890 -0.032340  0.663259        NaN   
2020-03-31  0.158849  0.051571  0.100390  0.000000 -0.167924        NaN   
2020-04-30  0.114751  0.118690  0.152126  0.151935 -0.214890        NaN   
2020-05-31 -0.025454 -0.009026 -0.003460  0.026914 -0.013383        NaN   
2020-06-30 -0.017476 -0.019145 -0.019865 -0.022119 -0.346252        NaN   
2020-07-31  0.537725  0.496305  0.482881  0.471773  0.694155        NaN   
2020-08-31  0.081098  0.173252  0.128583  0.172930  0.265762        NaN   
2020-09-30 -0.038801 -0.104706 -0.051617 -0.097225 -0.431546        NaN   
2020-10-31 -0.057003 -0.063178 -0.079717 -0.081717 -0.003584        NaN   
2020-11-30  0.132832  0.193565  0.165701  0.230708  0.645271        NaN   
2020-12-31  0.054620 -0.004744  0.050156 -0.010253 -0.704903        NaN   
2021-01-31 -0.049294 -0.043012 -0.064378 -0.066187  1.275740        NaN   
2021-02-28 -0.045569 -0.031020 -0.024818 -0.013195 -0.137002        NaN   
2021-03-31 -0.083762 -0.075476 -0.077072 -0.071116 -0.108315        NaN   
2021-04-30  0.083584  0.062808  0.064036  0.039745  0.067394        NaN   
2021-05-31 -0.051946 -0.035791 -0.033898 -0.018868 -0.121223        NaN   
2021-06-30  0.154589  0.163399  0.151792  0.172952  0.726907        NaN   
2021-07-31  0.118696  0.133878  0.118985  0.130523  0.775514        NaN   
2021-08-31  0.095079  0.040105  0.075459  0.042659 -0.607070        NaN   
2021-09-30 -0.082509 -0.061298 -0.064569 -0.070629  0.167200        NaN   
2021-10-31  0.184855  0.173592  0.175409  0.168416 -0.248291        NaN   
2021-11-30  0.349979  0.341764  0.298632  0.317225  0.736726        NaN   
2021-12-31 -0.104851 -0.096376 -0.077916 -0.091368 -0.342292        NaN   

            Stock Splits  
Date                      
2020-01-31           NaN  
2020-02-29           NaN  
2020-03-31           NaN  
2020-04-30           NaN  
2020-05-31           NaN  
2020-06-30           NaN  
2020-07-31           NaN  
2020-08-31           NaN  
2020-09-30           NaN  
2020-10-31           NaN  
2020-11-30           NaN  
2020-12-31           NaN  
2021-01-31           NaN  
2021-02-28           NaN  
2021-03-31           NaN  
2021-04-30           NaN  
2021-05-31           NaN  
2021-06-30           NaN  
2021-07-31           NaN  
2021-08-31           NaN  
2021-09-30           NaN  
2021-10-31           NaN  
2021-11-30           NaN  
2021-12-31           NaN

In [ ]:
# we can fill nan data for use in our analysis

daily_return.fillna(0)

Open      High       Low     Close    Volume  Dividends  \
Date                                                                      
2020-01-31  0.000000  0.000000  0.000000  0.000000  0.000000        0.0   
2020-02-29 -0.145455 -0.050021 -0.122890 -0.032340  0.663259        0.0   
2020-03-31  0.158849  0.051571  0.100390  0.000000 -0.167924        0.0   
2020-04-30  0.114751  0.118690  0.152126  0.151935 -0.214890        0.0   
2020-05-31 -0.025454 -0.009026 -0.003460  0.026914 -0.013383        0.0   
2020-06-30 -0.017476 -0.019145 -0.019865 -0.022119 -0.346252        0.0   
2020-07-31  0.537725  0.496305  0.482881  0.471773  0.694155        0.0   
2020-08-31  0.081098  0.173252  0.128583  0.172930  0.265762        0.0   
2020-09-30 -0.038801 -0.104706 -0.051617 -0.097225 -0.431546        0.0   
2020-10-31 -0.057003 -0.063178 -0.079717 -0.081717 -0.003584        0.0   
2020-11-30  0.132832  0.193565  0.165701  0.230708  0.645271        0.0   
2020-12-31  0.054620 -0.004744  0.050156 -0.010253 -0.704903        0.0   
2021-01-31 -0.049294 -0.043012 -0.064378 -0.066187  1.275740        0.0   
2021-02-28 -0.045569 -0.031020 -0.024818 -0.013195 -0.137002        0.0   
2021-03-31 -0.083762 -0.075476 -0.077072 -0.071116 -0.108315        0.0   
2021-04-30  0.083584  0.062808  0.064036  0.039745  0.067394        0.0   
2021-05-31 -0.051946 -0.035791 -0.033898 -0.018868 -0.121223        0.0   
2021-06-30  0.154589  0.163399  0.151792  0.172952  0.726907        0.0   
2021-07-31  0.118696  0.133878  0.118985  0.130523  0.775514        0.0   
2021-08-31  0.095079  0.040105  0.075459  0.042659 -0.607070        0.0   
2021-09-30 -0.082509 -0.061298 -0.064569 -0.070629  0.167200        0.0   
2021-10-31  0.184855  0.173592  0.175409  0.168416 -0.248291        0.0   
2021-11-30  0.349979  0.341764  0.298632  0.317225  0.736726        0.0   
2021-12-31 -0.104851 -0.096376 -0.077916 -0.091368 -0.342292        0.0   

            Stock Splits  
Date                      
2020-01-31           0.0  
2020-02-29           0.0  
2020-03-31           0.0  
2020-04-30           0.0  
2020-05-31           0.0  
2020-06-30           0.0  
2020-07-31           0.0  
2020-08-31           0.0  
2020-09-30           0.0  
2020-10-31           0.0  
2020-11-30           0.0  
2020-12-31           0.0  
2021-01-31           0.0  
2021-02-28           0.0  
2021-03-31           0.0  
2021-04-30           0.0  
2021-05-31           0.0  
2021-06-30           0.0  
2021-07-31           0.0  
2021-08-31           0.0  
2021-09-30           0.0  
2021-10-31           0.0  
2021-11-30           0.0  
2021-12-31           0.0

In [ ]:
# or with the next value
daily_return = amd_by_month_agg.pct_change()
daily_return.fillna(method='bfill')

Open      High       Low     Close    Volume  Dividends  \
Date                                                                      
2020-01-31 -0.145455 -0.050021 -0.122890 -0.032340  0.663259        NaN   
2020-02-29 -0.145455 -0.050021 -0.122890 -0.032340  0.663259        NaN   
2020-03-31  0.158849  0.051571  0.100390  0.000000 -0.167924        NaN   
2020-04-30  0.114751  0.118690  0.152126  0.151935 -0.214890        NaN   
2020-05-31 -0.025454 -0.009026 -0.003460  0.026914 -0.013383        NaN   
2020-06-30 -0.017476 -0.019145 -0.019865 -0.022119 -0.346252        NaN   
2020-07-31  0.537725  0.496305  0.482881  0.471773  0.694155        NaN   
2020-08-31  0.081098  0.173252  0.128583  0.172930  0.265762        NaN   
2020-09-30 -0.038801 -0.104706 -0.051617 -0.097225 -0.431546        NaN   
2020-10-31 -0.057003 -0.063178 -0.079717 -0.081717 -0.003584        NaN   
2020-11-30  0.132832  0.193565  0.165701  0.230708  0.645271        NaN   
2020-12-31  0.054620 -0.004744  0.050156 -0.010253 -0.704903        NaN   
2021-01-31 -0.049294 -0.043012 -0.064378 -0.066187  1.275740        NaN   
2021-02-28 -0.045569 -0.031020 -0.024818 -0.013195 -0.137002        NaN   
2021-03-31 -0.083762 -0.075476 -0.077072 -0.071116 -0.108315        NaN   
2021-04-30  0.083584  0.062808  0.064036  0.039745  0.067394        NaN   
2021-05-31 -0.051946 -0.035791 -0.033898 -0.018868 -0.121223        NaN   
2021-06-30  0.154589  0.163399  0.151792  0.172952  0.726907        NaN   
2021-07-31  0.118696  0.133878  0.118985  0.130523  0.775514        NaN   
2021-08-31  0.095079  0.040105  0.075459  0.042659 -0.607070        NaN   
2021-09-30 -0.082509 -0.061298 -0.064569 -0.070629  0.167200        NaN   
2021-10-31  0.184855  0.173592  0.175409  0.168416 -0.248291        NaN   
2021-11-30  0.349979  0.341764  0.298632  0.317225  0.736726        NaN   
2021-12-31 -0.104851 -0.096376 -0.077916 -0.091368 -0.342292        NaN   

            Stock Splits  
Date                      
2020-01-31           NaN  
2020-02-29           NaN  
2020-03-31           NaN  
2020-04-30           NaN  
2020-05-31           NaN  
2020-06-30           NaN  
2020-07-31           NaN  
2020-08-31           NaN  
2020-09-30           NaN  
2020-10-31           NaN  
2020-11-30           NaN  
2020-12-31           NaN  
2021-01-31           NaN  
2021-02-28           NaN  
2021-03-31           NaN  
2021-04-30           NaN  
2021-05-31           NaN  
2021-06-30           NaN  
2021-07-31           NaN  
2021-08-31           NaN  
2021-09-30           NaN  
2021-10-31           NaN  
2021-11-30           NaN  
2021-12-31           NaN

In [ ]:
# or we can simply ignore the data

daily_return = amd_by_month_agg.diff()
daily_return.dropna()

Open       High        Low      Close      Volume  Dividends  \
Date                                                                            
2020-02-29  -7.040001  -2.430000  -5.750000  -1.520000  40009400.0        0.0   
2020-03-31   6.570000   2.379997   4.119999   0.000000 -16848100.0        0.0   
2020-04-30   5.500000   5.760002   6.869999   6.910000 -17939800.0        0.0   
2020-05-31  -1.360001  -0.490002  -0.180000   1.410000   -877200.0        0.0   
2020-06-30  -0.910000  -1.029999  -1.029999  -1.189999 -22391000.0        0.0   
2020-07-31  27.509998  26.189999  24.540001  24.820000  29345900.0        0.0   
2020-08-31   6.380005  13.680000   9.690002  13.389999  19034300.0        0.0   
2020-09-30  -3.300003  -9.699997  -4.389999  -8.830002 -39122200.0        0.0   
2020-10-31  -4.660004  -5.240005  -6.430000  -6.699997   -184700.0        0.0   
2020-11-30  10.240005  15.040001  12.299995  17.370003  33134000.0        0.0   
2020-12-31   4.769997  -0.439995   4.340004  -0.950005 -59552300.0        0.0   
2021-01-31  -4.540001  -3.970001  -5.850006  -6.070000  31805100.0        0.0   
2021-02-28  -3.989998  -2.740005  -2.109993  -1.129997  -7772900.0        0.0   
2021-03-31  -7.000000  -6.459999  -6.390007  -6.010002  -5303400.0        0.0   
2021-04-30   6.400002   4.970001   4.900002   3.120003   2942400.0        0.0   
2021-05-31  -4.309998  -3.010002  -2.759995  -1.540001  -5649200.0        0.0   
2021-06-30  12.159996  13.250000  11.939995  13.849998  29768800.0        0.0   
2021-07-31  10.779999  12.630005  10.779999  12.260002  54845500.0        0.0   
2021-08-31   9.660004   4.290001   7.650002   4.529999 -76228000.0        0.0   
2021-09-30  -9.180000  -6.820000  -7.040001  -7.820000   8249500.0        0.0   
2021-10-31  18.869995  18.129997  17.889999  17.330002 -14298700.0        0.0   
2021-11-30  42.330002  41.890007  35.799995  38.139992  31892700.0        0.0   
2021-12-31 -17.119995 -15.850006 -12.129990 -14.470001 -25734400.0        0.0   

            Stock Splits  
Date                      
2020-02-29           0.0  
2020-03-31           0.0  
2020-04-30           0.0  
2020-05-31           0.0  
2020-06-30           0.0  
2020-07-31           0.0  
2020-08-31           0.0  
2020-09-30           0.0  
2020-10-31           0.0  
2020-11-30           0.0  
2020-12-31           0.0  
2021-01-31           0.0  
2021-02-28           0.0  
2021-03-31           0.0  
2021-04-30           0.0  
2021-05-31           0.0  
2021-06-30           0.0  
2021-07-31           0.0  
2021-08-31           0.0  
2021-09-30           0.0  
2021-10-31           0.0  
2021-11-30           0.0  
2021-12-31           0.0

### Dataframe

In [ ]:
''' a Dataframe is pratically a table that organize and allow manipulation
   of data sets'''

import pandas as pd
dict = {'AAPL': [124.5, 124.09, 162.77, 124.18, 193.77],'GOOG':[698.7, 411.71, 906.69, 718.59, 226.99],
        'IBM':[134.58, 151.67, 132.56, 112.94, 253.49]}
data_index = pd.date_range('2017-07-03',periods = 5, freq = 'D')
df = pd.DataFrame(dict, index = data_index)
df

AAPL    GOOG     IBM
2017-07-03  124.50  698.70  134.58
2017-07-04  124.09  411.71  151.67
2017-07-05  162.77  906.69  132.56
2017-07-06  124.18  718.59  112.94
2017-07-07  193.77  226.99  253.49

In [ ]:
# we can access data by column

print(df['GOOG'])
print(df.IBM)

# as shown before ressampling and ranges work on dataframes

2017-07-03    698.70
2017-07-04    411.71
2017-07-05    906.69
2017-07-06    718.59
2017-07-07    226.99
Freq: D, Name: GOOG, dtype: float64
2017-07-03    134.58
2017-07-04    151.67
2017-07-05    132.56
2017-07-06    112.94
2017-07-07    253.49
Freq: D, Name: IBM, dtype: float64


In [ ]:
# we can get more subset from a dataframe
df.loc['2017-07-03':'2017-07-05',['IBM', 'AAPL']]

IBM    AAPL
2017-07-03  134.58  124.50
2017-07-04  151.67  124.09
2017-07-05  132.56  162.77

In [ ]:
# also can apply logic statements
df.loc[df['IBM'] < 150]

AAPL    GOOG     IBM
2017-07-03  124.50  698.70  134.58
2017-07-05  162.77  906.69  132.56
2017-07-06  124.18  718.59  112.94

In [ ]:
# we can add dta very easily
df['return_IBM'] = df.IBM.diff()

In [ ]:
df

AAPL    GOOG     IBM  return_IBM
2017-07-03  124.50  698.70  134.58         NaN
2017-07-04  124.09  411.71  151.67       17.09
2017-07-05  162.77  906.69  132.56      -19.11
2017-07-06  124.18  718.59  112.94      -19.62
2017-07-07  193.77  226.99  253.49      140.55

In [ ]:
#we can see where is a nan value

df.isnull()
df = df.fillna(0)

In [ ]:
df

AAPL    GOOG     IBM  return_IBM
2017-07-03  124.50  698.70  134.58        0.00
2017-07-04  124.09  411.71  151.67       17.09
2017-07-05  162.77  906.69  132.56      -19.11
2017-07-06  124.18  718.59  112.94      -19.62
2017-07-07  193.77  226.99  253.49      140.55

In [ ]:
# we can concat dataframes together
# axis 1 concat side by side
s1 = pd.Series([243.5, 544.09, 122.73, 784.18, 563.77], name = 'AAPL')
s2 = pd.Series([498.7, 231.71, 126.69, 788.59, 936.99], name = 'GOOG')
data_frame = pd.concat([s1,s2], axis = 1)
print(data_frame)

     AAPL    GOOG
0  243.50  498.70
1  544.09  231.71
2  122.73  126.69
3  784.18  788.59
4  563.77  936.99


In [113]:
import numpy as np
# axis 0 concat vertically
amd_s = amd.Close
pd.concat([amd_s, np.log(amd_s)], axis = 0)

Date
2020-01-02    49.099998
2020-01-03    48.599998
2020-01-06    48.389999
2020-01-07    48.250000
2020-01-08    47.830002
                ...    
2021-12-27     5.039288
2021-12-28     5.031418
2021-12-29     4.998967
2021-12-30     4.977768
2021-12-31     4.969119
Name: Close, Length: 1010, dtype: float64